export const metadata: Metadata = {
  title: "Privacy Policy",
  description:
    "Read the privacy policy for IELTSpeak. Learn how we collect, use, and protect your information when you use our application and services.",
};

import { Metadata } from "next";
import Link from "next/link";
import React from "react";

export default function PrivacyPolicy() {
  return (
    <>
      <div className="flex items-center justify-center mt-12 gap-1">
        <Link href="/">
          <h1 className="text-4xl text-center font-bold text-red-600">
            IELTSpeak
          </h1>
        </Link>
      </div>
      <div className=" py-12 px-4 sm:px-6 lg:px-8">
        <div className="max-w-3xl mx-auto bg-[#2F2F7F]/50 p-8 sm:p-12 rounded-lg shadow-md">
          <div className="prose prose-lg max-w-none">
            <h1>Privacy Policy for IELTSpeak</h1>
            <p className="text-sm text-gray-500">Last Updated: July 10, 2025</p>

            <p>
              Welcome to IELTSpeak. We are committed to protecting your privacy.
              This Privacy Policy explains how we collect, use, disclose, and
              safeguard your information when you use our application and
              services. By using IELTSpeak, you agree to the collection and use
              of information in accordance with this policy.
            </p>

            <h2>1. Information We Collect</h2>
            <p>
              We collect several different types of information for various
              purposes to provide and improve our service to you.
            </p>

            <h4>A. Personal and Account Information</h4>
            <ul>
              <li>
                <strong>Account Data:</strong> When you register for an account,
                we collect your email address and password, which are managed
                securely by our authentication provider.
              </li>
              <li>
                <strong>Profile Data:</strong> You may voluntarily provide us
                with additional profile information, such as your name, target
                IELTS band score, and contextual data (e.g., hometown,
                occupation) to personalize your practice sessions.
              </li>
            </ul>

            <h4>B. Session and Usage Data</h4>
            <ul>
              <li>
                <strong>Voice Recordings & Transcripts:</strong> During your
                practice sessions, we process your voice input in real-time. We
                may store the audio recordings and the resulting text
                transcripts of your sessions to provide you with a history and
                for analysis.
              </li>
              <li>
                <strong>AI-Generated Data:</strong> We store the results of your
                sessions, which include the JSON object containing your band
                score breakdown and the written feedback generated by our AI
                models.
              </li>
            </ul>

            <h4>C. Payment Information</h4>
            <ul>
              <li>
                When you subscribe to a paid plan, your payment is processed by
                our third-party payment processor,Lemon Squeezy. We do not
                collect or store your credit card details. We only receive a
                confirmation token and subscription status from Lemon Squeezy to
                manage your account.
              </li>
            </ul>

            <h2>2. How We Use Your Information</h2>
            <p>We use the collected data for the following purposes:</p>
            <ul>
              <li>
                To provide, maintain, and improve our application and its
                features.
              </li>
              <li>To create and manage your account.</li>
              <li>To conduct AI-powered speaking test simulations.</li>
              <li>
                To generate personalized suggestions and feedback based on your
                performance and profile data.
              </li>
              <li>
                To calculate and display your estimated IELTS band scores and
                session history.
              </li>
              <li>
                To process your subscriptions and payments through Lemon
                Squeezy.
              </li>
              <li>
                To communicate with you, including sending welcome emails or
                responding to your inquiries.
              </li>
            </ul>

            <h2>3. Third-Party Services and Data Sharing</h2>
            <p>
              We do not sell your personal information. We rely on trusted
              third-party services to provide our application, and we only share
              the necessary information with them:
            </p>
            <ul>
              <li>
                <strong>Backend & Database Services:</strong> We use trusted
                services for database storage, authentication, and security.
                Your profile data, session history, and encrypted user
                credentials are stored with these providers.
              </li>
              <li>
                <strong>Real-time Voice Processing:</strong> Your voice input is
                streamed to a third-party service to facilitate the live
                conversation with our AI examiner.
              </li>
              <li>
                <strong>Artificial Intelligence Models:</strong> We send session
                transcripts to third-party AI models to generate your scores,
                feedback, and real-time suggestions. We do not send personally
                identifiable information like your name or email in these
                requests.
              </li>
              <li>
                <strong>Payment Processing:</strong> We use an established
                third-party payment processor for handling all
                subscription-related billing.
              </li>
              <li>
                <strong>Email Delivery:</strong> We use a third-party email
                service for sending transactional emails (e.g., welcome emails,
                password resets).
              </li>
            </ul>

            <h2>4. Data Security</h2>
            <p>
              The security of your data is a top priority. We implement robust
              security measures to protect your information. Our database, uses
              Row Level Security (RLS), a powerful security feature that ensures
              you can only ever access your own data. All data is encrypted in
              transit and at rest.
            </p>

            <h2>5. Your Rights and Data Control</h2>
            <p>
              You have the right to access, update, or delete the information we
              have on you. You can review and update your profile information
              directly within your dashboard. If you wish to delete your account
              and all associated data, please contact us at the email address
              below.
            </p>

            <h2>6. Children's Privacy</h2>
            <p>
              Our service is not intended for use by children under the age of
              16. We do not knowingly collect personally identifiable
              information from children under 16. If we become aware that we
              have collected personal data from a child without verification of
              parental consent, we take steps to remove that information from
              our servers.
            </p>

            <h2>7. Changes to This Privacy Policy</h2>
            <p>
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page
              and updating the "Last Updated" date at the top. You are advised
              to review this Privacy Policy periodically for any changes.
            </p>

            <h2>8. Contact Us</h2>
            <p>
              If you have any questions about this Privacy Policy, please
              contact us through the main page{" "}
            </p>
          </div>
        </div>
      </div>
    </>
  );
}
